-- 元数据同名表在 public 下可建可用, system 名下 create 报已存在且 drop/insert/delete 拦截
CREATE TABLE db_table (id int);
INSERT INTO db_table VALUES (1);
SELECT * FROM db_table;
DROP TABLE db_table;
CREATE TABLE system.db_table (id int);
CREATE TABLE system.db_column (id int);
CREATE TABLE system.db_schema (id int);
DROP TABLE system.db_table;
DROP TABLE system.db_column;
DROP TABLE system.db_schema;
INSERT INTO system.db_table VALUES (1, 'x');
INSERT INTO system.db_column VALUES (1, 'x', 0, 1, 0, 1);
INSERT INTO system.db_schema VALUES (1, 'x');
DELETE FROM system.db_table;
DELETE FROM system.db_column;
DELETE FROM system.db_schema;
CREATE TABLE system.db_index (id int);
CREATE TABLE system.db_version (id int);
DROP TABLE system.db_index;
DROP TABLE system.db_version;
INSERT INTO system.db_index VALUES (1);
INSERT INTO system.db_version VALUES (1);
DELETE FROM system.db_index;
DELETE FROM system.db_version;
CREATE TABLE t_reserved (id int);
INSERT INTO t_reserved VALUES (7);
SELECT * FROM t_reserved;
SELECT table_name FROM system.db_table ORDER BY table_name;
SELECT col_name, ordinal, type, length, not_null FROM system.db_column ORDER BY col_name, ordinal;
SELECT schema_name FROM system.db_schema ORDER BY schema_name;
SELECT * FROM system.db_index;
SELECT * FROM system.db_version;
DROP TABLE t_reserved;
SELECT table_name FROM system.db_table ORDER BY table_name;
