CREATE TABLE db_table (id int);
CREATE TABLE db_column (id int);
CREATE TABLE db_schema (id int);
DROP TABLE db_table;
DROP TABLE db_column;
DROP TABLE db_schema;
INSERT INTO db_table VALUES (1, 'x');
INSERT INTO db_column VALUES (1, 'x', 0, 1, 0, 1);
INSERT INTO db_schema VALUES (1, 'x');
DELETE FROM db_table;
DELETE FROM db_column;
DELETE FROM db_schema;
CREATE TABLE db_index (id int);
CREATE TABLE db_version (id int);
DROP TABLE db_index;
DROP TABLE db_version;
INSERT INTO db_index VALUES (1);
INSERT INTO db_version VALUES (1);
DELETE FROM db_index;
DELETE FROM db_version;
CREATE TABLE t_reserved (id int);
INSERT INTO t_reserved VALUES (7);
SELECT * FROM t_reserved;
SELECT table_name, schema_id FROM db_table;
SELECT col_name, ordinal, type, length, not_null FROM db_column;
SELECT * FROM db_schema;
SELECT * FROM db_index;
SELECT * FROM db_version;
DROP TABLE t_reserved;
SELECT table_name, schema_id FROM db_table;
