CREATE TABLE t_user (id int, score double);
INSERT INTO t_user VALUES (1, 95.5);
INSERT INTO t_user VALUES (2, 60 + 30.5);
INSERT INTO t_user VALUES (3, 88.0);
DELETE FROM t_user;
DROP TABLE t_user;
CREATE TABLE t_d (id int, v int);
INSERT INTO t_d VALUES (1, 10);
INSERT INTO t_d VALUES (2, 20);
INSERT INTO t_d VALUES (3, 30);
INSERT INTO t_d VALUES (4, 40);
DELETE FROM t_d WHERE nosuch = 1;
DELETE FROM t_d WHERE v >= 30;
SELECT * FROM t_d;
DELETE FROM t_d WHERE v > 100;
-- 恒假条件删除: 0 行
DELETE FROM t_d WHERE false;
SELECT * FROM t_d;
DELETE FROM t_d WHERE v = 10 OR v = 20;
SELECT * FROM t_d;
DROP TABLE t_d;
