CREATE TABLE t_user (id int, score double);
INSERT INTO t_user VALUES (1, 95.5);
INSERT INTO t_user VALUES (2, 60 + 30.5);
INSERT INTO t_user VALUES (3, 88.0);
DROP TABLE t_user;
CREATE TABLE t_nullable (id int, name varchar, score double);
INSERT INTO t_nullable VALUES (1, 'alice', 90.5);
INSERT INTO t_nullable VALUES (NULL, NULL, NULL);
INSERT INTO t_nullable VALUES (2, 'bob', NULL);
INSERT INTO t_nullable VALUES (NULL, 'carol', 75.0);
SELECT * FROM t_nullable ORDER BY id, name;
INSERT INTO t_nullable VALUES (NULL + 1, 'dave', 60.0);
INSERT INTO t_nullable VALUES (NULL / 0, 'eve', 55.5);
INSERT INTO t_nullable VALUES (-NULL, 'frank', 50.0);
INSERT INTO t_nullable VALUES ('abc' + NULL, 'gina', 45.0);
SELECT id + 1 FROM t_nullable ORDER BY id;
SELECT * FROM t_nullable ORDER BY id, name;
DROP TABLE t_nullable;
CREATE TABLE t_cols (id int, name varchar, score double);
INSERT INTO t_cols (id, name, score) VALUES (1, 'alice', 90.5);
INSERT INTO t_cols (id) VALUES (2);
INSERT INTO t_cols (name, score) VALUES ('bob', 60.5);
INSERT INTO t_cols (score) VALUES (75.0);
INSERT INTO t_cols (name) VALUES (NULL);
INSERT INTO t_cols (score, id) VALUES (50.0, 3);
INSERT INTO t_cols (id, score) VALUES (4, 10 + 5.5);
SELECT * FROM t_cols ORDER BY id, name, score;
DROP TABLE t_cols;
CREATE TABLE t_multi (id int, name varchar, score double);
INSERT INTO t_multi VALUES (1, 'alice', 90.5), (2, 'bob', 60.0), (3, 'carol', 75.5);
INSERT INTO t_multi VALUES (4, 'dave', NULL), (NULL, NULL, NULL);
INSERT INTO t_multi VALUES (5, 'eve', 50 + 25.5), (6, 'frank', NULL / 0);
SELECT * FROM t_multi ORDER BY id;
INSERT INTO t_multi VALUES (7), (8, 'gina', 40.0);
INSERT INTO t_multi VALUES (9, 'henry', 10.0), (10, 20, 20.0);
INSERT INTO t_multi (id, score) VALUES (11, 1.0), (12, 2.0);
INSERT INTO t_multi (id, score) VALUES (14, 4.0), (15);
SELECT * FROM t_multi ORDER BY id;
DROP TABLE t_multi;
