CREATE TABLE t_user (id int, score double);
INSERT INTO t_user VALUES (1, 95.5);
INSERT INTO t_user VALUES (2, 60 + 30.5);
INSERT INTO t_user VALUES (3, 88.0);
DROP TABLE t_user;
CREATE TABLE t_nullable (id int, name varchar, score double);
INSERT INTO t_nullable VALUES (1, 'alice', 90.5);
INSERT INTO t_nullable VALUES (NULL, NULL, NULL);
INSERT INTO t_nullable VALUES (2, 'bob', NULL);
INSERT INTO t_nullable VALUES (NULL, 'carol', 75.0);
SELECT * FROM t_nullable;
INSERT INTO t_nullable VALUES (NULL + 1, 'dave', 60.0);
INSERT INTO t_nullable VALUES (NULL / 0, 'eve', 55.5);
INSERT INTO t_nullable VALUES (-NULL, 'frank', 50.0);
INSERT INTO t_nullable VALUES ('abc' + NULL, 'gina', 45.0);
SELECT id + 1 FROM t_nullable;
SELECT * FROM t_nullable;
DROP TABLE t_nullable;
