CREATE TABLE t_upd (id int, name varchar, score double);
INSERT INTO t_upd VALUES (1, 'alice', 90.5), (2, 'bob', 60.0), (3, 'carol', 75.0);
UPDATE t_upd SET score = 100.0 WHERE id = 1;
SELECT * FROM t_upd ORDER BY id;
UPDATE t_upd SET name = 'dave' WHERE id > 1;
SELECT * FROM t_upd ORDER BY id;
UPDATE t_upd SET score = score + 0.5;
SELECT * FROM t_upd ORDER BY id;
UPDATE t_upd SET id = 9 WHERE id = 100;
-- 恒假条件更新: 0 行
UPDATE t_upd SET score = 0.0 WHERE false;
UPDATE t_upd SET id = id + 10, score = score * 2.0 WHERE id <= 12;
SELECT * FROM t_upd ORDER BY id;
DROP TABLE t_upd;
CREATE TABLE t_swap (a int, b int);
INSERT INTO t_swap VALUES (1, 2), (3, 4);
UPDATE t_swap SET a = b, b = a;
SELECT * FROM t_swap ORDER BY a;
DROP TABLE t_swap;
CREATE TABLE t_err (id int NOT NULL, n int, name varchar(8));
INSERT INTO t_err VALUES (1, 10, 'alice'), (2, NULL, 'bob');
UPDATE t_err SET id = n;
SELECT * FROM t_err ORDER BY id;
UPDATE t_err SET id = n WHERE name = 'alice';
SELECT * FROM t_err ORDER BY id;
UPDATE t_err SET name = 'xx';
SELECT * FROM t_err ORDER BY id;
DROP TABLE t_err;
CREATE TABLE t_len (short varchar(4), src varchar(10));
INSERT INTO t_len VALUES ('ab', 'abcdefghij');
UPDATE t_len SET short = src;
SELECT * FROM t_len;
UPDATE t_len SET src = short;
SELECT * FROM t_len;
DROP TABLE t_len;
CREATE TABLE t_ovf (id int);
INSERT INTO t_ovf VALUES (1);
UPDATE t_ovf SET id = 2000000000 + 2000000000;
SELECT * FROM t_ovf;
DROP TABLE t_ovf;
CREATE TABLE t_char (c char(6), v varchar(6));
INSERT INTO t_char VALUES ('ab', 'xy');
UPDATE t_char SET v = c;
SELECT * FROM t_char;
UPDATE t_char SET c = v;
SELECT c FROM t_char;
DROP TABLE t_char;
