CREATE TABLE t_si (a int, b bigint, c double, f float, s char(3), v varchar(5));
INSERT INTO t_si VALUES ('x', 1, 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (1.5, 1, 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (2147483648, 1, 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (1, 'x', 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (1, 1, 'x', 1.0, 'a', 'a');
INSERT INTO t_si VALUES (1, 1, 1.0, 'x', 'a', 'a');
INSERT INTO t_si VALUES (1, 1, 1, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (1, 1, 1.0, 1.0, 'abcd', 'a');
INSERT INTO t_si VALUES (1, 1, 1.0, 1.0, 'a', 'abcdef');
INSERT INTO t_si VALUES (1, 2);
INSERT INTO t_si VALUES (1 > 2, 1, 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (NULL, 1, 1.0, 1.0, 'a', 'a');
INSERT INTO t_si VALUES (a, 1, 1.0, 1.0, 'a', 'a');
INSERT INTO nosuch_si VALUES (1);
INSERT INTO t_si VALUES (1, 2, 3.0, 4.0, 'ab', 'abcde');
SELECT * FROM t_si ORDER BY a;
DROP TABLE t_si;
CREATE TABLE t_ic (a int, b double, s varchar);
INSERT INTO t_ic (nosuch) VALUES (1);
INSERT INTO t_ic (a, a) VALUES (1, 2);
INSERT INTO t_ic (a, b) VALUES (1);
INSERT INTO t_ic (a, b) VALUES (1, 2, 3);
INSERT INTO t_ic (a) VALUES ('x');
INSERT INTO t_ic (b, a) VALUES ('x', 1);
INSERT INTO t_ic (b) VALUES (1 > 2);
INSERT INTO t_ic (a) VALUES (b);
INSERT INTO t_ic (a, s) VALUES (NULL, 'ok');
SELECT * FROM t_ic;
DROP TABLE t_ic;
CREATE TABLE t_sn (a int NOT NULL, b int, s varchar(4) not null);
INSERT INTO t_sn VALUES (1, NULL, 'x');
INSERT INTO t_sn VALUES (NULL, 1, 'x');
INSERT INTO t_sn (b) VALUES (1);
INSERT INTO t_sn (a, s) VALUES (1, NULL);
INSERT INTO t_sn VALUES (1, 2);
INSERT INTO t_sn VALUES (2, NULL, 'y'), (NULL, 3, 'z');
INSERT INTO t_sn VALUES (3, 4, 'ok'), (5, 6, 'no');
SELECT * FROM t_sn ORDER BY a;
DROP TABLE t_sn;
