CREATE TABLE t_ss (i int, s char(4), f double);
SELECT i + s FROM t_ss;
SELECT -s FROM t_ss;
SELECT i FROM t_ss WHERE i + s;
SELECT i FROM t_ss WHERE 1;
SELECT i FROM t_ss WHERE s AND i > 0;
SELECT i FROM t_ss WHERE NOT i;
SELECT i FROM t_ss WHERE i > s;
SELECT i > 1 FROM t_ss;
SELECT i FROM t_ss WHERE nosuch_ss;
INSERT INTO t_ss VALUES (1, 'ab', 1.5);
SELECT i + 1 FROM t_ss;
SELECT i FROM t_ss WHERE i > 0;
SELECT -i FROM t_ss WHERE NOT (i > 10);
DROP TABLE t_ss;
-- order by 报错: 列不存在/序号越界/输出名歧义/非整数常量/比较两侧类型不符
CREATE TABLE t_so (i int, s char(4), f double);
SELECT i FROM t_so ORDER BY nosuch;
SELECT i AS x FROM t_so ORDER BY y;
SELECT i AS x, s AS x FROM t_so ORDER BY x;
SELECT i FROM t_so ORDER BY 0;
SELECT i FROM t_so ORDER BY 2;
SELECT i FROM t_so ORDER BY 'c';
SELECT i FROM t_so ORDER BY 1.5;
SELECT i FROM t_so ORDER BY NULL;
SELECT i FROM t_so ORDER BY true;
SELECT i FROM t_so ORDER BY nosuch + 1;
SELECT i FROM t_so ORDER BY i > s;
SELECT 1 AS x, 2 AS x ORDER BY x;
SELECT 1 ORDER BY nosuch;
SELECT 1 ORDER BY 'c';
DROP TABLE t_so;
