SET table_id = 4;
set table_id = 4;
SeT TABLE_ID = 4;
SET table_id = -1;
SET schema_id = 1;
SET unknown_var = 0;
SET table_id;
SET table_id = ;
SET = 4;
CREATE TABLE set (a int);
SET client_msg_level = warning;
SET client_msg_level = 'debug';
SET client_msg_level = INFO;
SET client_msg_level = banana;
SET client_msg_level = 5;
SET client_msg_level = table_id;
