CREATE TABLE idx_t (id int, name varchar(20), score double);
CREATE INDEX idx_a ON idx_t (id);
create index idx_a on idx_t (score);
CREATE INDEX idx_b ON idx_t (name);
CREATE INDEX idx_c ON idx_t (no_col);
CREATE INDEX idx_d ON no_table (id);
CREATE INDEX idx_e ON db_table (table_id);
CREATE INDEX ON idx_t (id);
CREATE INDEX idx_f idx_t (id);
CREATE INDEX idx_g ON idx_t id;
INSERT INTO idx_t VALUES (1, 'a', 1.5);
INSERT INTO idx_t VALUES (2, NULL, NULL);
DROP INDEX idx_z ON idx_t;
DROP INDEX idx_a ON idx_t;
DROP INDEX idx_a ON idx_t;
DROP INDEX idx_a ON no_table;
DROP INDEX idx_a ON db_table;
DROP INDEX idx_a;
CREATE TABLE idx_u (v bigint);
CREATE INDEX idx_a ON idx_u (v);
BEGIN;
CREATE INDEX idx_h ON idx_t (id);
CREATE INDEX idx_a ON idx_t (score);
SELECT * FROM idx_t;
DROP TABLE idx_u;
DROP TABLE idx_t;
SELECT * FROM db_index;
